kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: golang:1.14
  commands:
    - go build -v -ldflags '-w -extldflags '-static''
  environment:
    CGO_ENABLED: 0
    GOPROXY: https://proxy.golang.org

- name: container
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/observatorium/namespace-provisioner
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
  when:
    branch:
    - master
    event:
    - push
