apiVersion: v1
kind: Namespace
metadata:
  name: namespace-provisioner
  labels:
    app.kubernetes.io/name: namespace-provisioner
    app.kubernetes.io/part-of: namespace-provisioner
---
apiVersion: v1
kind: Secret
metadata:
  name: namespace-provisioner
  namespace: namespace-provisioner
  labels:
    app.kubernetes.io/name: namespace-provisioner
    app.kubernetes.io/part-of: namespace-provisioner
stringData:
  token: PASSWORD
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-provisioner
  namespace: namespace-provisioner
  labels:
    app.kubernetes.io/name: namespace-provisioner
    app.kubernetes.io/part-of: namespace-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-provisioner
  labels:
    app.kubernetes.io/name: namespace-provisioner
    app.kubernetes.io/part-of: namespace-provisioner
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - namespace-provisioner
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - bind
  resourceNames:
  - namespace-provisioner-grant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-provisioner
  labels:
    app.kubernetes.io/name: namespace-provisioner
    app.kubernetes.io/part-of: namespace-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-provisioner
subjects:
  - kind: ServiceAccount
    namespace: namespace-provisioner
    name: namespace-provisioner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-provisioner
  namespace: namespace-provisioner
  labels:
    app.kubernetes.io/name: namespace-provisioner
    app.kubernetes.io/part-of: namespace-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: namespace-provisioner
      app.kubernetes.io/part-of: namespace-provisioner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: namespace-provisioner
        app.kubernetes.io/part-of: namespace-provisioner
    spec:
      serviceAccountName: namespace-provisioner
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: namespace-provisioner
        image: quay.io/observatorium/namespace-provisioner
        imagePullPolicy: IfNotPresent
        args:
        - --listen=:8080
        - --listen-internal=:9090
        - --cluster-role=namespace-provisioner-grant
        - --token=$(TOKEN)
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: namespace-provisioner
              key: token
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
